layout_spectrum: 0.5043546154629439
typography_spectrum: 0.7713278313167393
color:
  brandStrength: 0.9228666285052896
  lightness: 0.22586580272763968
  saturation: 0.5204336238093674
  rhythmicContrast: 0.44242560351267457
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
analytics:
  google: UA-82657126-1
author:
  name: Stefan Van den Bossche
  email: mangoamusic@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/643ab330-d09c-4698-a6cf-746a530fa868.jpg
name: MangoA
navigation:
  - name: Home
    url: 'http://mangoa.world'
    type: external
  - name: Our History
    url: 'http://thegrid.ai/mangoa_history/'
    type: external
  - name: Video
    url: 'https://www.youtube.com/channel/UCzloqvz-OFRjT26Htjl4v6w'
    type: external
  - name: Audio
    url: 'https://soundcloud.com/mangoa/tracks'
    type: external
  - name: Photos
    url: 'https://thegrid.ai/mangoa_photos/'
    type: external
  - name: Upcoming Shows
    url: 'http://thegrid.ai/mangoa_shows/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/Mangoa-197941767016658/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1fcb342a-25ac-4ca4-bae6-48e627963690.ico
title: ''
