typography_spectrum: 0.6493998111691326
color:
  brandStrength: 0.6802509820554405
  lightness: 0.8484585194382817
  saturation: 0.7353550235275179
  rhythmicContrast: 0.6220963224768639
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
layout_spectrum: 0.07202306017279625
analytics:
  google: UA-82657126-1
author:
  name: Stefan Van den Bossche
  email: mangoamusic@gmail.com
logo: null
name: MangoA
navigation:
  - name: Home
    url: mangoa.world
    type: external
  - name: Our History
    url: 'http://thegrid.ai/mangoa_history/'
    type: external
  - name: Video
    url: 'https://www.youtube.com/channel/UCzloqvz-OFRjT26Htjl4v6w'
    type: external
  - name: Audio
    url: 'https://soundcloud.com/mangoa/tracks'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/Mangoa-197941767016658/'
    type: external
  - name: Upcoming Shows
    url: 'http://thegrid.ai/mangoa_shows/'
    type: external
  - name: Photos
    id: c280bcde-ac6c-4bbf-afec-ea9c931a9060
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1fcb342a-25ac-4ca4-bae6-48e627963690.ico
title: ''
