typography_spectrum: 0.42924265074543655
color:
  brandStrength: 0.11933297291398048
  lightness: 0.5249492994043976
  saturation: 0.8474352904595435
  rhythmicContrast: 0.25985998730175197
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
layout_spectrum: 0.027662486070767045
author:
  name: Stefan Van den Bossche
  email: mangoamusic@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d59c5a96-c492-4f7c-9645-4da138206851.jpg
name: MangoA
navigation:
  - name: Our History
    url: 'http://thegrid.ai/mangoa_history/'
    type: external
  - name: Our History3
    id: a481f39f-6ed6-4e3b-90b9-181f6ce4d307
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/Mangoa-197941767016658/'
    type: external
  - name: Soundcloud
    url: 'https://soundcloud.com/mangoa/tracks'
    type: external
  - name: Video
    url: 'https://www.youtube.com/channel/UCzloqvz-OFRjT26Htjl4v6w'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1fcb342a-25ac-4ca4-bae6-48e627963690.ico
title: ''
