typography_spectrum: 0.42924265074543655
color:
  brandStrength: 0.11933297291398048
  lightness: 0.5249492994043976
  saturation: 0.8474352904595435
  rhythmicContrast: 0.25985998730175197
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
layout_spectrum: 0.027662486070767045
author:
  name: Stefan Van den Bossche
  email: mangoamusic@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/50a8b0f4-1c6e-44cd-8c38-99109e9c7908.jpg
name: MangoA
navigation:
  - id: 50e3bc56-12f8-4570-981c-54e059bcfc14
    url: 2016-07-24-our-history.html
    name: Our History
    type: content
  - id: 'https://soundcloud.com/mangoa/tracks'
    url: 'https://soundcloud.com/mangoa/tracks'
    name: Soundcloud
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fec4ab4c-07c5-4a81-b21e-742a8cacac49.zip
title: ''
